export interface Project {
  slug: string;
  title: string;
  category: "ml" | "nlp" | "dl" | "data" | "app" | "ai";
  description: string;
  problem?: string;
  solution?: string;
  metrics?: { label: string; value: string }[];
  tags: string[];
  github?: string;
  live?: string;
  featured: boolean;
  tier: 1 | 2 | 3;
}

export const projectsData: Project[] = [
  {
    slug: "statwise",
    title: "StatWise",
    category: "app",
    description: "Automated statistical reporting platform that transforms raw datasets into analysis-ready reports and visual insights for SMEs.",
    problem: "Small businesses struggle to extract meaningful insights from their data without dedicated analysts or expensive BI tools.",
    solution: "Built an end-to-end platform that accepts CSV/Excel uploads, runs automated statistical analyses, generates visualizations, and produces downloadable PDF reports with actionable recommendations.",
    metrics: [
      { label: "Accuracy", value: "94%" },
      { label: "Report Generation", value: "<30s" },
      { label: "Data Types", value: "20+" },
    ],
    tags: ["Python", "FastAPI", "Pandas", "Scikit-learn", "PostgreSQL", "Plotly"],
    live: "https://statwise-te5z.onrender.com/",
    github: "https://github.com/siumahameed",
    featured: true,
    tier: 1,
  },
  {
    slug: "vocabpro",
    title: "VocabPro",
    category: "app",
    description: "SaaS platform delivering daily English vocabulary with Bengali meanings via WhatsApp and email, featuring AI chatbot and gamification.",
    problem: "English learners in Bangladesh lack consistent, contextual vocabulary practice in their native language.",
    solution: "Developed a subscription-based service with automated daily vocabulary delivery, AI-powered chatbot with 6 personas, weekly quizzes, and streak tracking.",
    tags: ["FastAPI", "PostgreSQL", "WhatsApp API", "AI", "Email"],
    live: "https://vocabpro-dgow.onrender.com/",
    github: "https://github.com/siumahameed",
    featured: true,
    tier: 1,
  },
  {
    slug: "heart-disease-prediction",
    title: "Heart Disease Prediction",
    category: "ml",
    description: "Predicting heart disease risk using classification algorithms on patient medical data with comprehensive model evaluation.",
    problem: "Early detection of heart disease risk can significantly improve patient outcomes and reduce healthcare costs.",
    solution: "Built and compared multiple classification models (Logistic Regression, Random Forest, XGBoost) with feature importance analysis and cross-validation.",
    metrics: [
      { label: "Best Model", value: "XGBoost" },
      { label: "F1 Score", value: "0.91" },
      { label: "CV Folds", value: "5" },
    ],
    tags: ["Python", "Scikit-learn", "XGBoost", "Healthcare", "Classification"],
    github: "https://github.com/siumahameed/ml_projects/tree/main/heart_disease_prediction",
    featured: true,
    tier: 2,
  },
  {
    slug: "bd-road-accident-analysis",
    title: "BD Road Accident Analysis",
    category: "data",
    description: "Comprehensive analysis of road accident patterns in Bangladesh to identify key causes, trends, and safety recommendations.",
    problem: "Bangladesh faces high road accident rates, but data-driven insights for policy and safety improvements are limited.",
    solution: "Performed extensive EDA on accident datasets, identified patterns across time, location, and vehicle types, and generated actionable visualizations for stakeholders.",
    tags: ["Python", "Pandas", "Matplotlib", "Seaborn", "EDA"],
    github: "https://github.com/siumahameed/Eda-projects-basic-/tree/main/BD%20Road%20Accident%20Analysis",
    featured: true,
    tier: 2,
  },
  {
    slug: "bd-temperature-rain-analysis",
    title: "BD Temperature & Rain Analysis",
    category: "data",
    description: "Analyzing temperature and rainfall patterns across Bangladesh to identify seasonal and regional climate trends.",
    problem: "Understanding climate patterns is crucial for agriculture, infrastructure planning, and disaster preparedness in Bangladesh.",
    solution: "Analyzed multi-year weather data to uncover seasonal trends, regional variations, and correlations between temperature and rainfall patterns.",
    tags: ["Python", "Pandas", "Matplotlib", "Plotly", "EDA"],
    github: "https://github.com/siumahameed/Eda-projects-basic-/tree/main/Bangladesh%20Temperature%20and%20Rain%20Analysis",
    featured: true,
    tier: 2,
  },
  {
    slug: "agritech",
    title: "AgriTech",
    category: "app",
    description: "AI-powered agricultural advisory platform for Bangladeshi farmers with Bengali chatbot, crop recommendations, and disease detection.",
    problem: "Bangladeshi farmers lack access to timely, localized agricultural advice in their native language.",
    solution: "Built a full-stack platform with Bengali NLP chatbot, image-based crop disease detection, fertilizer calculator, and government subsidy information.",
    tags: ["Node.js", "AI", "Tailwind CSS", "JavaScript"],
    live: "https://agritech-fwib.onrender.com/",
    github: "https://github.com/siumahameed",
    featured: true,
    tier: 1,
  },
  {
    slug: "spam-sms-detection",
    title: "Spam SMS Detection",
    category: "nlp",
    description: "NLP project to detect spam messages using TF-IDF vectorization and supervised machine learning classifiers.",
    tags: ["Python", "NLP", "TF-IDF", "Scikit-learn", "Text Classification"],
    github: "https://github.com/siumahameed/ml_projects/tree/main/spam_sms_detection",
    featured: false,
    tier: 3,
  },
  {
    slug: "sonar-prediction",
    title: "Rock and Mine Prediction",
    category: "ml",
    description: "Predicting whether an object is a mine or rock using Logistic Regression on sonar radar data.",
    tags: ["Python", "Scikit-learn", "Logistic Regression", "Classification"],
    github: "https://github.com/siumahameed/ml_projects/tree/main/submarine_sonar_project",
    featured: false,
    tier: 3,
  },
  {
    slug: "ad-click-prediction",
    title: "Ad Click Prediction",
    category: "ml",
    description: "Predicting user ad clicks using classification models for better targeting and campaign optimization.",
    tags: ["Python", "Scikit-learn", "ML", "Classification"],
    github: "https://github.com/siumahameed/ml_projects/tree/main/Ad_click_project",
    featured: false,
    tier: 3,
  },
  {
    slug: "energy-consumption",
    title: "Energy Consumption Prediction",
    category: "ml",
    description: "Forecasting energy consumption using regression models for better resource planning.",
    tags: ["Python", "ML", "Regression", "Data Analysis"],
    github: "https://github.com/siumahameed/ml_projects/tree/main/Energy%20Consumption%20Project",
    featured: false,
    tier: 3,
  },
  {
    slug: "loan-prediction",
    title: "Loan Prediction",
    category: "ml",
    description: "Predicting loan approval status based on applicant details using classification algorithms.",
    tags: ["Python", "Scikit-learn", "Classification", "Finance"],
    github: "https://github.com/siumahameed/ml_projects/tree/main/Loand%20Prediction",
    featured: false,
    tier: 3,
  },
  {
    slug: "ipl-analysis",
    title: "IPL Data Analysis",
    category: "data",
    description: "Comprehensive analysis of Indian Premier League cricket data to extract team and player insights.",
    tags: ["Python", "Pandas", "Visualization", "EDA"],
    github: "https://github.com/siumahameed/Eda-projects-basic-/tree/main/IPL%20Data%20Analysis",
    featured: false,
    tier: 3,
  },
  {
    slug: "diwali-sales",
    title: "Diwali Sales Analysis",
    category: "data",
    description: "Analyzing Diwali sales data to understand customer purchasing patterns and product trends.",
    tags: ["Python", "Pandas", "Matplotlib", "EDA"],
    github: "https://github.com/siumahameed/Eda-projects-basic-/tree/main/Diwali%20Sales%20Analysis",
    featured: false,
    tier: 3,
  },
  {
    slug: "us-shop-analysis",
    title: "Shop Data Analysis",
    category: "data",
    description: "Analyzing US retail shop data to understand sales patterns and customer behavior.",
    tags: ["Python", "Pandas", "Tableau", "EDA"],
    github: "https://github.com/siumahameed/Eda-projects-basic-/tree/main/Us%20shop%20data%20analysis",
    featured: false,
    tier: 3,
  },
  {
    slug: "lego-analysis",
    title: "Lego Data Analysis",
    category: "data",
    description: "Exploratory analysis of Lego product datasets to explore sets, themes, and trends.",
    tags: ["Python", "Pandas", "Data Visualization", "EDA"],
    github: "https://github.com/siumahameed/Eda-projects-basic-/tree/main/lego%20analysis",
    featured: false,
    tier: 3,
  },
  {
    slug: "bd-cricket-analysis",
    title: "BD Cricket Analysis",
    category: "data",
    description: "Exploratory data analysis of Bangladesh cricket statistics and performance metrics.",
    tags: ["Python", "Pandas", "Data Visualization", "EDA"],
    github: "https://github.com/siumahameed/Eda-projects-basic-/tree/main/BD%20Cricket%20Analysis",
    featured: false,
    tier: 3,
  },
];
